#ifndef DEFINATIONS_H
#define DEFINATIONS_H

#define VOICE_ID_LENGTH 32
#define GUILD_ID_LENGTH 32
#define USER_ID_LENGTH 32
#define SESSION_ID_LENGTH 128
#define TRACK_LENGTH 512

#define COGLINK_LOADTYPE_NO_MATCHES 5
#define COGLINK_LOADTYPE_LOAD_FAILED 4
#define COGLINK_LOADTYPE_SEARCH_RESULT 3
#define COGLINK_LOADTYPE_PLAYLIST_LOADED 2
#define COGLINK_LOADTYPE_TRACK_LOADED 1

#define COGLINK_PROCEED 2
#define COGLINK_IGNORE 1
#define COGLINK_SUCCESS 0
#define COGLINK_STOP -1

#define COGLINK_JSMNF_ERROR_PARSE -2
#define COGLINK_JSMNF_ERROR_LOAD -3
#define COGLINK_JSMNF_ERROR_FIND -4

#define COGLINK_LIBCURL_FAILED_INITIALIZE -5
#define COGLINK_LIBCURL_FAILED_SETOPT -6
#define COGLINK_LIBCURL_FAILED_PERFORM -7

#define COGLINK_OPTIONAL_FEATURE_NOT_ENABLED -8
#define COGLINK_NOT_FOUND -9

#endif