#ifndef DEFINATIONS_H
#define DEFINATIONS_H

enum {
  COGLINK_PROCEED = 2,
  COGLINK_IGNORE = 1,
  COGLINK_SUCCESS = 0,
  COGLINK_STOP = -1,
  COGLINK_JSMNF_ERROR_PARSE = -2,
  COGLINK_JSMNF_ERROR_LOAD = -3,
  COGLINK_JSMNF_ERROR_FIND = -4,
  COGLINK_LIBCURL_FAIL_INITIALIZE = -5,
  COGLINK_LIBCURL_FAIL_SETOPT = -6,
  COGLINK_LIBCURL_FAIL_PERFORM = -7
};

#endif