#ifndef DEFINATIONS_H
#define DEFINATIONS_H

#define FILTER_VOLUME 0
#define FILTER_EQUALIZER 1
#define FILTER_KARAOKE 2
#define FILTER_TIMESCALE 3
#define FILTER_TREMOLO 4
#define FILTER_ROTATION 5
#define FILTER_DISTORTION 6
#define FILTER_CHANNELMIX 7
#define FILTER_LOWPASS 8
#define FILTER_REMOVE 9

#define ROUTERPLANNER_CLASS_LENGTH 26

#define LAVALINK_SESSIONID_LENGTH 17

#define DISCORD_TOKEN_LENGTH 17

#define VOLUME_LENGTH 8
#define TOKEN_LENGTH 128
#define ENDPOINT_LENGTH 64
#define SESSIONID_LENGTH 16
#define PING_LENGTH 8

#define VOICE_ID_LENGTH 32
#define GUILD_ID_LENGTH 32
#define USER_ID_LENGTH 32
#define SESSION_ID_LENGTH 128
#define TRUE_FALSE_LENGTH 8

#define TRACK_LENGTH 256
#define IDENTIFIER_LENGTH 13
#define TRACK_TITLE_LENGTH 100
#define PLAYLIST_NAME_LENGTH 64
#define AUTHOR_NAME_LENGTH 30
#define VIDEO_LENGTH 16
#define URL_LENGTH 44
#define SOURCENAME_LENGTH 10

#define COGLINK_WAIT 103

#define COGLINK_LOADTYPE_NO_MATCHES 5
#define COGLINK_LOADTYPE_LOAD_FAILED 4
#define COGLINK_LOADTYPE_SEARCH_RESULT 3
#define COGLINK_LOADTYPE_PLAYLIST_LOADED 2
#define COGLINK_LOADTYPE_TRACK_LOADED 1

#define COGLINK_PROCEED 2
#define COGLINK_IGNORE 1
#define COGLINK_SUCCESS 0
#define COGLINK_STOP -1

#define COGLINK_JSMNF_ERROR_PARSE -2
#define COGLINK_JSMNF_ERROR_LOAD -3
#define COGLINK_JSMNF_ERROR_FIND -4

#define COGLINK_LIBCURL_FAILED_INITIALIZE -5
#define COGLINK_LIBCURL_FAILED_SETOPT -6
#define COGLINK_LIBCURL_FAILED_PERFORM -7

#define COGLINK_ROUTERPLANNER_NOT_SET -8

#define COGLINK_ERROR -9

#endif
